# Generated by Django 4.2.2 on 2023-06-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'Ratings'},
        ),
    ]
