# Generated by Django 4.2.2 on 2023-06-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings', '0002_alter_ratings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'Rating'},
        ),
    ]
