# Generated by Django 4.2.2 on 2023-06-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Login'},
        ),
    ]
